### PR TITLE
Updated interactive

### PR DESCRIPTION
**Pull request by vidartf**
PS: This PR is based on some of my other PRs to your branches, so there's a bit of a dependence tree and merge-conflicts to manage.

### CODE REVIEW

**Comment by dnjohnstone** [comment]
@vidartf The diff on this is absolutely massive - not totally sure why but it includes all of the separation of Model2D bits, which it shouldn't now I don't think.

**Comment by vidartf** [comment]
@dnjohnstone One of the reasons is that this PR includes a merge of master, which the base does not have. It also includes updated merges from the events branches (#423 plus my PR to that). Some of those merges have conflicts, which probably means we need to do some rebasing and such to get this in, but that's what happens with so many interdependent branches being worked on by different people.

**Comment by dnjohnstone** [comment]
ah yes - so presumably the options are: 1. francisco merges up the base with the master and we hope the diff becomes managable, or 2. francisco just accepts this pull request and we look at the diff in the PR to the main HyperSpy project?

**Comment by vidartf** [comment]
Probably best option is for @francisco-dlp to manually merge my merge commit 1fdd070 into his branch, i.e. `git cherry-pick 1fdd070` after fetching my branch locally.

Actually, I should probably PR that alone...

**Comment by vidartf** [comment]
Or, I have no idea what is best to do actually. I'll leave it @francisco-dlp and whatever git-fu he knows :)

**Comment by francisco-dlp** [comment]
I'll go for the simplest solution, merging it.

**Pull request merged**
