### PR TITLE
[SPLIT-IO] Keep support for passing hyperspy to `file_write`

### PR DESCRIPTION
**Pull request by ericpre**
Even `file_writer` are not explicitly part of the public API, I suspect that this may be used in the wild, so we should try to avoid this API, where possible. 
Using a decorator, this can be done easily for all writers.

### CODE REVIEW

**Comment by francisco-dlp** [comment]
I am not sure if this is necessary. If `file_writer` is used be external packages even if it is not part of the API, the developers will need to change their code anyway because they'll have to import from `rsciio` instead of `hyperspy`. Therefore, while updating the package, they can also update what they are passing to `file_writer`.

**Comment by ericpre** [comment]
Are you saying that `hyperspy.io_plugins.msa.file_reader` will be removed in hyperspy 1.8.0? To avoid breaking it, we could deprecate its usage by adding a "wrapper" of `rsciio.plugins` in `hyperspy.pluings` and recommend using `rsciio` and remove it in hyperspy 2.0.
Should I add the "wrapper" in this PR?

**Comment by francisco-dlp** [comment]
You cannot access `file_writer` it through the user API `hyperspy.api`. However, strictly speaking, you are right, `file_writer` is in the hyperspy API, since it is not a private method. If we take this strict view, we must not indeed break the API in 1.8.0. In that case, I personally prefer to release it as HyperSpy 2.0, rather than adding a wrapper. Like this we'll also get rid of all the `DeprecationWarning`s that we have accumulated over the years ;)

**Comment by ericpre** [comment]
Yes, this will work too and I don't think that there will be that much work required to release hyperspy 2.0 if we don't split the EDS and EELS as mentioned previously.

**Comment by francisco-dlp** [comment]
Once that's ready we can release HyperSpy 3.0.

Anyway, I bet that splitting the TEM part is a lot easier than the IO code since all the machinery is already in place. Currently I lean towards putting everything TEM into a TEM package e.g. HyperSTEM. Of course it won't have everything TEM, but it'll host everything that is small enough not to need its own package—basically everything that is currently in hyperspy. What do you think?

**Comment by jlaehne** [comment]
can this be closed now?

**Comment by ericpre** [comment]
Yes, this is not necessary since the IO split will be released with HyperSpy 2.0 and the API will break.

**Pull request closed without merging**
