### PR TITLE
Axis argument improved

### PR DESCRIPTION
**Pull request by vidartf**
Cleaned up `Signal._apply_function_on_data_and_remove_axis()`, and split off some function into a separate function `Signal._get_iaxes()` for reusability. Fixed `EDSSignal.sum()` to use `axis` argument as well, and cleaned up two minor issues.

### CODE REVIEW

**Comment by vidartf** [comment]
I've merged current master into this one as well in order to resolve a conflict in `EDSSignal.sum()`, so if you merge master into your branch first the diff should be a lot cleaner.

**Comment by francisco-dlp** [comment]
There is an issue with this PR, 370 files changed!

**Comment by vidartf** [comment]
Isn't it because I merged master?

**Comment by francisco-dlp** [comment]
Sure, sorry, I went through this too quickly. Two tests are failing though, any idea why?

**Comment by vidartf** [comment]
Yes, I just pushed a fix.

**Comment by francisco-dlp** [comment]
My master is up-to-date but the problem persists.

2015-12-18 15:51 GMT+00:00 Vidar Tonaas Fauske notifications@github.com:

**Comment by vidartf** [comment]
I'm rebasing.

**Comment by vidartf** [comment]
Could you rebase your `ENH_axis_argument` branch? I'm getting some difficult merge conflicts as this branch is outdated.

**Comment by francisco-dlp** [comment]
I have just merged master into it.I think that it's not good practice to
rebase once the code is up in github because rebasing changes the history.
I did the mistake last week.

2015-12-18 16:19 GMT+00:00 Vidar Tonaas Fauske notifications@github.com:

**Comment by vidartf** [comment]
Sorry, I mean merge master :) And yes, if you do force push, you have to make sure no-one has used your old code for anything.

**Comment by vidartf** [comment]
Now everything in this PRs diff is neat, but I see I have a small error to fix before merging.

**Comment by vidartf** [comment]
All CI is green, so please consider merging :)

**Comment by francisco-dlp** [comment]
Nice, sorry again for not getting the merging issue before.

**Comment by vidartf** [comment]
No worries :)

**Pull request merged**
