### PR TITLE
Enh axis argument

### PR DESCRIPTION
**Pull request by vidartf**
Added check for dimensions change in `out` in `_apply_function_on_data_and_remove_axis`. If the dimensions have changed, it calls `out.get_dimensions_from_data()`, which will also trigger a replot if `auto_replot is True`.

### CODE REVIEW

**Comment by francisco-dlp** [comment]
Isn't this dangerous? If the dimensions have changed, by calling `get_dimensions_from_data` we may be getting the calibration wrong, isn't it?

**Comment by vidartf** [comment]
I'm sorry, wrong branch :)

**Comment by vidartf** [comment]
Regarding whether it is dangerous or not, I'm not entirely sure. `_get_dimensions_from_data` modifies the `size` parameter on the axis, so as long as the offset and scale is unchanged, it should be ok. I'm most worried about the offset being wrong, especially if this is cut with an ROI. Wouldn't matter much for spatial dimensions (which are relative), but for energy and other absolute scales it is of course important.

**Comment by vidartf** [comment]
On the other hand, if the dimensions of `out` has changed, something definitely has to be done. Using `_get_dimensions_from_data` was my best bet.

**Comment by francisco-dlp** [comment]
I the dimensions change for a good reason then we have to do something about it, but, why would the dimensions change?

**Comment by vidartf** [comment]
Well, your example script from #425, with a minor change, should give a decent example:

``` python
roi = utils.roi.RectangularROI(0, 0, 10, 10)
s = signals.Spectrum(np.random.random((10, 20, 100)))
s.axes_manager[0].scale = 0.5
s.axes_manager[0].scale = 0.1
sroi = roi.interactive(s)
# If we sum over only one navigator dimension (here 'x'), instead of two, 
# changing roi will change size of sroi, and consequently ssum
ssum = utils.interactive(sroi.sum, event=sroi.events.data_changed, axis="x")
ssum.plot()
```

This example would be useful for making e.g. a line profile tool. Here,
- `roi` changes, triggers `roi.events.changed`
- `roi.__call__()` calls `s.__getitem__()` with `out=sroi`.
  - `s.__getitem__()` calls `sroi._get_dimensions_from_data` (always has).
- `s.__getitem__()` triggers `sroi.events.data_changed`
- `sroi.sum` is called, but it's data shape has changed. Trying to update the draw of ssum will fail (either silently or with exception).

This being said, it doesn't seem like `Signal.__getitem__()` pays any mind to calibration (i.e. offset)?

**Comment by francisco-dlp** [comment]
I see. What about solving the issue as follows?:

``` python

class Interactive:
    def __init__(self, f, event,
                 recompute_out_event=None,
                 *args, **kwargs):

        self.f = f
        self.args = args
        self.kwargs = kwargs
        if kwargs.has_key('out'):
            self.f(*args, **kwargs)
            self.out = kwargs.pop('out')
        else:
            self.out = self.f(*args, **kwargs)
            if recompute_out_event:
                recompute_out_event.connect(self._recompute_out)
        event.connect(self.update)

    def _recompute_out(self):
        out = self.f(self.args, self.kwargs)
        self.out.data = out.data
        self.out.__dict__.update(out.__dict__)

    def update(self, *args, **kwargs):
        self.f(out=self.out, *self.args, **self.kwargs)
```

This is of course less convenient because the user has to provide an extra event, but it shouldn't mess up the calibration.

It may be possible to write a more convenient solution by recovering the `obj` argument and connecting `_recompute_out` to the right event. What do yo think?

**Comment by vidartf** [comment]
I'm not sure. Either way we have to make sure `Signal.__getitem__(out=out)` updates the `offset` of what it is slicing (should be easy to fix since it has access to the slices). Currently, I think this is the only function on Signal (with an `out` parameter) that actually changes the shape/calibration. The rest is just an issue of having it propagate correctly down to any other Signals that uses this as a source. The question is, do we introduce a new `data_resized` event, do the check on Signal, or have subscriber of `data_changed` check?

Your suggested `_recompute_out` is powerful, in that whatever has changed will be picked up, but has a couple of problems, the biggest of which is that it will change `Interactive.out` from what was returned from the initial call to `interactive()``, basically causing a disconnect.

I've struggled quite a bit with figuring out a way to put the code in the right place, so that it can get the info it needs, can fire Events naturally, and generally not make things rigid and brittle. Putting it on `Interactive`, I cannot find such a way. Putting it in `_apply_function_on_data_and_remove_axis()`, I think this modification on the end check should work:

``` python
if oldshape != out.data.shape:
    for axis in out.axes_manager._axes:
        src_axis = None
        for sa in self.axes_manager._axes:
            if sa.name == axis.name:
                src_axis = sa
                break
        if src_axis is not None:
            axis.offset = src_axis.offset
    out.get_dimensions_from_data()
out.events.data_changed.trigger()
```

**Comment by vidartf** [comment]
Note that either way, if the offset changes in `__getitem__()`, ROIs can become invalid since they use values and not indices. E.g.:

``` python
roi = utils.roi.RectangularROI(10, 10, 20, 50)
s = signals.Spectrum(np.random.random((100, 100, 100)))
roi2 = utils.roi.RectangularROI(10, 10, 13, 30)
roi.right = 90
roi.left = 80 
# What is expected behavior for roi2 here? 
# To update from 10:13 to 80:83 on x?
```

**Comment by vidartf** [comment]
I just noticed that `Signal.__getitem__()` actually handles offsets correctly via the `_slice_me()` function on `DataAxis`, so that's one fewer problem to worry about :)

**Comment by francisco-dlp** [comment]
Yes, I was just going to write you about this, but you found it out on your own.

**Comment by francisco-dlp** [comment]
> Your suggested _recompute_out is powerful, in that whatever has changed will be picked up, but has a couple of problems, the biggest of which is that it will change Interactive.out from what was returned from the initial call to interactive()`, basically causing a disconnect.

I agree, but we can solve this issue by transferring the connections, isn't it?

I prefer to solve the problem in `Interactive` instead of `_apply_function_on_data_and_remove_axis` because it is a more general approach. If we were to "patch"  `_apply_function_on_data_and_remove_axis()` we will have to do the same for all functions taking an "out" argument.

**Comment by vidartf** [comment]
> I agree, but we can solve this issue by transferring the connections, isn't it?

It's not necessarily that trivial. Consider this case:

``` python
roi = utils.roi.RectangularROI(0, 0, 5, 5)
s = signals.Spectrum(np.random.random((10, 20, 100)))
sroi = roi.interactive(s)
ssum = utils.interactive(sroi.sum, event=sroi.events.data_changed, axis='x')
smax = utils.interactive( ssum.max, event=ssum.events.data_changed, axis='y')
smax.plot()
```

If we navigate `roi` in `s`, then ssum will update its data. This will trigger `data_changed` which will try to redo sroi.sum. If we do `_recompute_out` for sroi.sum, and transfer the `data_changed` subscribers, then the ssum.max which we passed to utils.interactive earlier will still be left dangling (i.e. it is the sum operator on the wrong Signal).

Other problems that occur when we don't fix the internal state of `out` before triggering events, is that all subscribers need to check for the change in size, meaning that code has to be replicated to the consumer end (where a user is more likely to sit).

>  If we were to "patch" _apply_function_on_data_and_remove_axis() we will have to do the same for all functions taking an "out" argument. 

Yes, I know, but currently, this seems the least painful. However, I might have another solution: Could we have Interactive connect the axes_managers? Suggested sketch:

``` python
class InteractiveSignal(Interactive):
    def __init__(self, source, f, event, *args, **kwargs):
        super(InteractiveSignal, self).__init__(f, event, *args, **kwargs)
        if source is not None:
            lut = {a.name: a for a in self.out.axes_manager._axes}
            for axis in source.axes_manager:
                if axis.name not in lut:
                    continue
                # Should maybe add check for axes equality as well
                # in case f() modifies an axes
                axis.on_trait_change(self.axis_changed, ['offset', 'scale', 'size'])

    def axis_changed(self, obj, name, old, new):
        ax_name = obj.name
        dest = None
        for a in self.out.axes_manager._axes:
            if a.name == ax_name:
                dest = a
                break
        if dest is None:
            return
        dest.offset = obj.offset
        dest.size = obj.size
        dest.scale = obj.scale

def interactive_signal(source, f, event, *args, **kwargs):
    cls = InteractiveSignal(source, f, event, *args, **kwargs)
    return cls.out
```

**Comment by vidartf** [comment]
PS: Note that by putting the solution on `Interactive`, anything else that uses the `Signal` functions that has an `out` argument will not benefit from the fix.

**Comment by francisco-dlp** [comment]
Yes, it is not that trivial, but I think that it is a solvable problem and, once we get it right, it'll be solved for good.

Your new solution is more general than the previous one and, certainly, it is good enough for our current purposes. However, if in the future someone wants to write a function and make it interactive he'll have to think about how to implement the interactivity, which is a non trivial problem. The whole point of HyperSpy is having a data analysis software that is developed by its users. The majority of HyperSpy's users are researchers not computer scientist, so, for the project to be sustainable, I think that it is important to make it as easy as possible to contribute new features.

Going back to your concern, I don't see the problem. `_recompute_out` just changes the  `data` attribute and the axes of `out`, but `out` is still the same `ssum` object that we have passed to the next interactive function. Therefore, as long as when the first `interactive` `out` changes we recompute the second `interactive` `out` we should be fine, unless I'm getting something wrong.

**Comment by vidartf** [comment]
Well, I misunderstood `_recompute_out()` a little, but the `__dict__.update()` will (I think), overwrite the `events` attribute on `Interactive.out` (and it will overwrite the data attribute, so it's doing double assignment to data). It will also overwrite the axes_manager, so anything connected to the old axes' traits will drop off. As far as I can see it will also overwrite `_plot`, which just messes things up.

That being said, I completely agree with you on keeping the code base as simple and straight forward as possible, so let me try to break it down to basics:
- The functionality we want to have is for the functions on Signal that normally return a new Signal instance also have the ability to instead output to an existing Signal.
- The issue we're facing happens when the Signal passed as `out` doesn't have an axes_manager that fits with the data written to it. For the traditional use of `_apply_function_on_data_and_remove_axis` (i.e. no `out`), the correct axes for the output is achieved by starting with a copy, and then removing certain of the axes. With the `out` keyword, these steps are skipped, as they are assumed to already be correct.
- Currently, if a Signal is passed to `_apply_function_on_data_and_remove_axis` by `out`, we risk that the returned Signal will have an invalid state after the function returns. Currently, the state will also be invalid when the function fires its `data_changed` event.
- While `Interactive` is currently the main consumer of the `out` keyword abilities, it isn't (and shouldn't) be exclusively intended for it.

The question then boils down to: Should the functions that take an `out` parameter assume that the passed Signal has a fitting axes_manager? If yes, then using a Signal that changes it's calibration as a source for Interactive will necessarily be a bit of a hack (as it needs to step in and fix the invalid state before any other consumer tries to use it, which doesn't work well with events). If no, it becomes a question of how to implement it in as painless a process as possible (I have a new suggestion at end).

Another point that speaks for having the function be responsible, is the it is the only one that truly has control over what it did to the signal, e.g. which axes were removed, rebinned, offset etc. For sum()/max()/min()/etc this is straight forward, but Interactive should preferably be general and handle all use scenarios. I don't think it will be able to.

I said earlier that I had a suggestion for a low-cost way of fixing this on Signal, so please consider it:

``` python
class Signal:
    [...]
    def _update_axes_from(self, axes_manager):
        self_lut = {a.name: a for a in self.axes_manager._axes}
        for src_axis in axes_manager._axes:
            if src_axis.name not in self_lut:
                new_axis = src_axis.copy()
                new_axis.axes_manager = self.axes_manager
                idx = axes_manager._axes.index(src_axis)
                self.axes_manager._axes.insert(idx)
            dst_axis = self_lut.pop(src_axis.name)
            dst_axis.offset = src_axis.offset
            dst_axis.size = src_axis.size
            dst_axis.scale = src_axis.scale
        for rem_axis in self_lut.values():
            self._axes.remove(rem_axis)
        return self
```

This would allow the existing functions to only need this simple change:

``` python
if out is None:
    s = self._deepcopy_with_new_data(None)
else:
    s = out._update_axes_from(self.axes_manager)   # This line is the only change
```

PS: As you can see, I also added handling for cases where there are too many/few axes, just for completeness, but this could easily be removed (if so, I'd suggest having it trigger a warning).

**Comment by vidartf** [comment]
OK, now I've been arguing back and forth with myself here, and I think you're actually right; at least in the organization of it. I think I've been able to figure out a way to fix the issues I had with your initial suggestion. Let me just work them out and test it a bit, and I'll submit a proposed update.

**Comment by francisco-dlp** [comment]
Nice to hear that. Your remarks were all very interesting but none of them seemed serious enough to disregard the full approach.

**Comment by vidartf** [comment]
Ok, see my proposed solution in d0d822e1cb66078a83be0f92a1f264bfd02d257a. The only thing missing there is that some replots are not happening as they should.

**Comment by francisco-dlp** [comment]
Nice. It is unsurprising that the plots are not updating correctly: the 
line drawing code assumes that the number of points of the data remains 
constant.

There is one thing that I don't understand: why do you need 
`DataAxis._origin_id` at all? The situation that we're discussing 
involves axes that change size and/or calibration, but not axes that 
disappear. So, wouldn't it be safe to assume that the signal returned by 
`self.f(*args, **kwargs)` and `out` has the same axes just with 
different calibrations. And if the answer is yes, isn't `_origin_id` 
unnecessary then?

Last but not least, why didn't you forked 
@francisco-dlp/hyperspy/NEW_Interactive branch and send a PR to it? By 
working in your NEW_ROI branch we make the problem of reviewing the 
massive amount of changes there bigger...

**Comment by vidartf** [comment]
> Nice. It is unsurprising that the plots are not updating correctly: the line drawing code assumes that the number of points of the data remains constant.

There are other problems as well. I'll post some example cases later.

> why do you need `DataAxis._origin_id` at all?

In honesty, that's a remnant from a different attempt at a solution, but it should still be needed for the use of `_update_calibration_from()` in `Signal.__getitem__()`. If we slice one axes to a length of 1, that axes will be removed. Now, the current `_update_calibration_from()` doesn't handle this correctly, but when axes need to be reinserted `_origin_id` would be necessary to figure out order, and which axes correspond to each other. I initially though I could use their name for this, but found out that unnamed axes change their name when axes are added/removed.

> why didn't you fork ...

That was just due to time restrictions today (but note that while my NEW_ROI was the base for this commit, I'm not committing anything to that branch anymore). I'm working on hyperspy as the same time as I use it to analyze my data, so everything's a bit of a mess. When I realized the mistaken base, I prioritized getting a clean diff out for discussion. I'll clean that up later on, hopefully tomorrow.

**Comment by francisco-dlp** [comment]
> If we slice one axes to a length of 1, that axes will be removed.

Are you sure?

``` python

>>> s = signals.Spectrum(np.random.random((10,20,30)))
>>> s
<Spectrum, title: , dimensions: (20, 10|30)>
>>> s[0:1]
<Spectrum, title: , dimensions: (1, 10|30)>

```

I think that slicing (and therefore applying a ROI) shouldn't remove any axes, and if they do, that's a bug, isn't it? And that would be a relief because having to deal with axes removal would make things more complex and brittle.

Regarding working with branches, what I normally do is to have a "working" branch where I don't actually commit anything: it's just for merging all the branches that I need for working with HyperSpy. Every time that I need to change the code I do it in the relevant branch or I create a new one, I commit and go back to my working branch and merge the changes. It sounds cumbersome but, in the end, it saves time and keeps things tidy.

**Comment by vidartf** [comment]
> Are you sure?

Well, in `__getitem__` you have this code:

``` python
for slice_, axis in zip(slices, _signal.axes_manager._axes):
    if (isinstance(slice_, slice) or
            len(_signal.axes_manager._axes) < 2):
        array_slices.append(axis._slice_me(slice_))
    else:
        if isinstance(slice_, float):
            slice_ = axis.value2index(slice_)
        array_slices.append(slice_)
        _signal._remove_axis(axis.index_in_axes_manager)
```

As far as I can tell, this means that if an index is passed instead of a slice, it will simply remove that axis from the signal. Using your example to test it:

``` python
>>> s = signals.Spectrum(np.random.random((10,20,30)))
>>> s
<Spectrum, title: , dimensions: (20, 10|30)>
>>> s[0:1]
<Spectrum, title: , dimensions: (1, 10|30)>
>>> s[0]
<Spectrum, title: , dimensions: (10|30)>
```

Whether that's a bug, I don't know, but the code seems to made by intention.

**Comment by vidartf** [comment]
> Every time that I need to change the code I do it in the relevant branch or I create a new one, I commit and go back to my working branch and merge the changes.

Yes, I try to do the same thing, but once I start changing something, this happens: http://9gag.com/gag/aYp2mo2 :)

**Comment by francisco-dlp** [comment]
> As far as I can tell, this means that if an index is passed instead of a slice, it will simply remove that axis from the signal [...] Whether that's a bug, I don't know, but the code seems to made by intention.

No, that's not a bug: slicing doesn't remove axes, indexing does. But the point is that a ROI that slices shouldn't index, so changing a ROI's parameters should change the number of axes of the output, and therefore we shouldn't need to match the axes.

PS: the video is hilarious.

**Comment by vidartf** [comment]
> we shouldn't need to match the axes.

Alright, then I'll roll back the redundant changes, and flag it when it's up to date.

**Pull request closed without merging**
