### PR TITLE
[SPLIT-IO] last few tasks

### PR DESCRIPTION
**Pull request by ericpre**
As per https://github.com/hyperspy/hyperspy/pull/2972#issuecomment-1191200686:

Remaining tasks (from @ericpre's review):
* [x] Correct typo in folder name
* [x] Fully remove `rbg_tools`
* [x] Add tests for:
    * [x] `_obj_in_dict2hspy`
    * [x] `_dic_get_hs_obj_paths`

### CODE REVIEW

**Comment by jlaehne** [comment]
Tests are failing, because they still use the wrong spelling of rosettasciio, I added a PR that should fix them: https://github.com/ericpre/hyperspy/pull/22

**Review by jlaehne — APPROVED** [review]

**Comment by jlaehne** [comment]
Otherwise, lgtm!

**Comment by jlaehne** [comment]
Tests are have all run successful now. @francisco-dlp, if you can still merge this today, we could take care about the rest.

**Comment by francisco-dlp** [comment]
Great, thanks!

**Pull request merged**
