### PR TITLE
Event suppression safety feature

### PR DESCRIPTION
**Pull request by vidartf**
Added a boolean attribute to make sure an EventSuppressionContext only
does its **exit** cleanup once.

### CODE REVIEW

**Comment by francisco-dlp** [comment]
Why is this safety feature necessary i.e. how can your trigger `__exit__` more than once?

**Comment by vidartf** [comment]
When you get the context manager from Events.suppress, you can manually call `__enter__()` and `__exit__()`. Also, `__enter__` calls `__exit__` if there's an exception. This is just to make sure that if an exception is raised somewhere, this component will at least do it's job correctly :)

**Comment by vidartf** [comment]
To elaborate further: Context managers are basically syntactic sugar for a try-finally block, so even though we're using it as a utility (so one never forgets to release the suppression), I figured it should act nice around Exceptions. Might be overkill, but very little overhead a least :)

**Comment by francisco-dlp** [comment]
I'm not fully convinced by your arguments. `__enter__` and `__exit__` shouldn't be called manually and, if someone does it, it is at his own risk. `__enter__` calls `__exit__` but the loop is inside the try block so it shouldn't call `__exit__` more than once.

I think that we should keep the code as simple as possible so that it stays easy to maintain and the "user-becomes-contributor"  threshold remains low. So, unless this prevents bugs, I would rather prefer to keep it simple.

**Comment by vidartf** [comment]
I opted to add the extra bookkeeping to the context manager so that any misuse of those functions would have fewer and clearer (i.e. easier to track down) consequences. Of course, the safety checks in the context manager now simply fails silently. It might be better to throw an exception to indicate wrong use?
That being said, this discussion pointed out to me that I should look into my manual use of `__enter__` and `__exit__` from the widget code, and see if there is a better way of doing it (I could add `_suspend`/`_resume` functions on Events, hidden so people prefer `.suppress`).

**Comment by vidartf** [comment]
Either way, this functionality is in no way _needed_, so it can safely be left out.

**Comment by vidartf** [comment]
Issue fixed via vidartf/hyperspy#4.

**Pull request closed without merging**
