### PR TITLE
Fix references in documentation, ...

### PR DESCRIPTION
**Pull request by jlaehne**
* add intersphinx-mapping to rosettascio documentation
* fix references to hyperspy docs
* fix hyperspy reference to zspy reader
* add `_static` folder to avoid warning when compiling the docs
* add introductory paragraph to the documentation
* sort and link supported formats table, add exentsions column
* replace mentionings of HyperSpy by RosettaSciIO, where appropriate
* update io page in the HyperSpy docs
* replace mentionings of the hyperspy issue tracker.

Question: Where will the rosettascio documentation be located in the beginning? I set it up for `https://hyperspy.org/rosettasciio` in the hyperspy-doc-conf for the moment.

### Progress of the PR
- [x] Change implemented (can be split into several points),
- [x] update user guide (if appropriate),
- [x] ready for review.

### CODE REVIEW

**Comment by ericpre** [comment]
> Question: Where will the rosettascio documentation be located in the beginning? I set it up for `https://hyperspy.org/rosettasciio` in the hyperspy-doc-conf for the moment.

We can do something similar as for the [hyperspy-bundle](https://hyperspy.org/hyperspy-bundle) documentation, where there is a workflow to push the `gh-pages` branch, when suitable. the `pydata-sphinx-theme` has a nice a version switcher:
https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/configuring.html#add-a-dropdown-to-switch-between-docs-versions, which would be good to use.
The alternative is to use readthedocs only.

**Comment by jlaehne** [comment]
> > Question: Where will the rosettascio documentation be located in the beginning? I set it up for `https://hyperspy.org/rosettasciio` in the hyperspy-doc-conf for the moment.
> 
> We can do something similar as for the [hyperspy-bundle](https://hyperspy.org/hyperspy-bundle) documentation, where there is a workflow to push the `gh-pages` branch, when suitable. the `pydata-sphinx-theme` has a nice a version switcher: https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/configuring.html#add-a-dropdown-to-switch-between-docs-versions, which would be good to use. The alternative is to use readthedocs only.

Yes, could you set it up in analogy to the `hyperspy-bundle` once the new repository is created? At some point, I guess a new domain could be reserved ... but that is not one of the most urgent things.

**Comment by jlaehne** [comment]
@francisco-dlp have you decided on how to call the new repository? Then I could already adapt links to the issue tracker.

I guess, it will be `hyperspy/rosettsciio` (or `hyperspy/rsciio`)?

**Comment by francisco-dlp** [comment]
+1 for RosettaSciIO

**Comment by jlaehne** [comment]
I would say this PR is ready. Further improvements to the documentation can be be done after the split.

@ericpre does the used sphinx-theme allow to easily add an automated API documentation as for HyperSpy?

**Comment by ericpre** [comment]
> @ericpre does the used sphinx-theme allow to easily add an automated API documentation as for HyperSpy?

I haven't checked but I would imagine that this is standard, for example:
- https://matplotlib.org/3.5.2/api/index.html
- https://docs.scipy.org/doc/scipy/reference
- https://pandas.pydata.org/docs/reference/index.html
- https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html

**Comment by jlaehne** [comment]
> > @ericpre does the used sphinx-theme allow to easily add an automated API documentation as for HyperSpy?
> 
> I haven't checked but I would imagine that this is standard, for example:
> 
>     * https://matplotlib.org/3.5.2/api/index.html
> 
>     * https://docs.scipy.org/doc/scipy/reference
> 
>     * https://pandas.pydata.org/docs/reference/index.html
> 
>     * https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html

Well, just realized that an automated api documentation doesn't make sense ... instead, we will have to describe how to have load/write functions in other packages interface with `rsciio` plugins. But we should first do the split before working on that.

**Review by ericpre — APPROVED** [review]
Looks all good to me!

**Pull request merged**
